# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3308/bank?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jakarta.persistence.validation.mode=none
# Exclude unnecessary auto-configurations
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

# Ensure database schema is created before inserting data
spring.sql.init.mode=always

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.com.example.security=DEBUG

# TSA Configuration
tsa.url=https://timestamp.digicert.com
tsa.connect-timeout=5000
tsa.read-timeout=10000